# Generated by Django 4.2.1 on 2023-07-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0002_alter_useraccount_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_patient',
            field=models.BooleanField(default=True),
        ),
    ]
